namespace MyUtilities.CWS_14_8
{
    using System.CodeDom.Compiler;
    using System.ServiceModel;

    [ServiceContract(Namespace="urn:wsdl.ws.rightnow.com/v1_2", ConfigurationName="CWS_14_8.RightNowSyncPort"), GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface RightNowSyncPort
    {
        [ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(RequestErrorFaultType), Action="Batch", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), OperationContract(Action="Batch", ReplyAction="*"), FaultContract(typeof(ServerErrorFaultType), Action="Batch", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="Batch", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        BatchResponse Batch(BatchRequest request);
        [ServiceKnownType(typeof(RNFault)), OperationContract(Action="ConvertGenericToObject", ReplyAction="*"), FaultContract(typeof(UnexpectedErrorFaultType), Action="ConvertGenericToObject", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(ServerErrorFaultType), Action="ConvertGenericToObject", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="ConvertGenericToObject", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true)]
        ConvertGenericToObjectResponse ConvertGenericToObject(ConvertGenericToObjectRequest request);
        [OperationContract(Action="ConvertObjectToGeneric", ReplyAction="*"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(RequestErrorFaultType), Action="ConvertObjectToGeneric", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(ServerErrorFaultType), Action="ConvertObjectToGeneric", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), FaultContract(typeof(UnexpectedErrorFaultType), Action="ConvertObjectToGeneric", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        ConvertObjectToGenericResponse ConvertObjectToGeneric(ConvertObjectToGenericRequest request);
        [FaultContract(typeof(ServerErrorFaultType), Action="Create", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="Create", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), FaultContract(typeof(UnexpectedErrorFaultType), Action="Create", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="Create", ReplyAction="*")]
        CreateResponse Create(CreateRequest request);
        [ServiceKnownType(typeof(RNFault)), FaultContract(typeof(UnexpectedErrorFaultType), Action="Destroy", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), FaultContract(typeof(ServerErrorFaultType), Action="Destroy", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), OperationContract(Action="Destroy", ReplyAction="*"), FaultContract(typeof(RequestErrorFaultType), Action="Destroy", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        DestroyResponse Destroy(DestroyRequest request);
        [XmlSerializerFormat(SupportFaults=true), FaultContract(typeof(UnexpectedErrorFaultType), Action="ExecuteMarketingFlow", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="ExecuteMarketingFlow", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(ServerErrorFaultType), Action="ExecuteMarketingFlow", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="ExecuteMarketingFlow", ReplyAction="*"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), ServiceKnownType(typeof(RNFault))]
        ExecuteMarketingFlowResponse ExecuteMarketingFlow(ExecuteMarketingFlowRequest request);
        [ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(RequestErrorFaultType), Action="Get", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(RNFault)), FaultContract(typeof(UnexpectedErrorFaultType), Action="Get", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="Get", ReplyAction="*"), FaultContract(typeof(ServerErrorFaultType), Action="Get", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true)]
        GetResponse Get(GetRequest request);
        [ServiceKnownType(typeof(RNFault)), XmlSerializerFormat(SupportFaults=true), FaultContract(typeof(UnexpectedErrorFaultType), Action="GetFileData", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="GetFileData", ReplyAction="*"), FaultContract(typeof(RequestErrorFaultType), Action="GetFileData", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(ServerErrorFaultType), Action="GetFileData", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        GetFileDataResponse GetFileData(GetFileDataRequest request);
        [ServiceKnownType(typeof(AnalyticsReportSearchFilter)), ServiceKnownType(typeof(RNFault)), OperationContract(Action="GetMetaData", ReplyAction="*"), FaultContract(typeof(RequestErrorFaultType), Action="GetMetaData", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(ServerErrorFaultType), Action="GetMetaData", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="GetMetaData", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true)]
        GetMetaDataResponse GetMetaData(GetMetaDataRequest request);
        [FaultContract(typeof(UnexpectedErrorFaultType), Action="GetMetaDataForClass", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="GetMetaDataForClass", ReplyAction="*"), FaultContract(typeof(RequestErrorFaultType), Action="GetMetaDataForClass", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(ServerErrorFaultType), Action="GetMetaDataForClass", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault))]
        GetMetaDataForClassResponse GetMetaDataForClass(GetMetaDataForClassRequest request);
        [ServiceKnownType(typeof(RNFault)), OperationContract(Action="GetMetaDataLastChangeTime", ReplyAction="*"), FaultContract(typeof(ServerErrorFaultType), Action="GetMetaDataLastChangeTime", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="GetMetaDataLastChangeTime", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="GetMetaDataLastChangeTime", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(AnalyticsReportSearchFilter))]
        GetMetaDataLastChangeTimeResponse GetMetaDataLastChangeTime(GetMetaDataLastChangeTimeRequest request);
        [ServiceKnownType(typeof(AnalyticsReportSearchFilter)), OperationContract(Action="GetValuesForNamedID", ReplyAction="*"), FaultContract(typeof(UnexpectedErrorFaultType), Action="GetValuesForNamedID", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="GetValuesForNamedID", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), FaultContract(typeof(ServerErrorFaultType), Action="GetValuesForNamedID", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        GetValuesForNamedIDResponse GetValuesForNamedID(GetValuesForNamedIDRequest request);
        [FaultContract(typeof(ServerErrorFaultType), Action="GetValuesForNamedIDHierarchy", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="GetValuesForNamedIDHierarchy", ReplyAction="*"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(UnexpectedErrorFaultType), Action="GetValuesForNamedIDHierarchy", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="GetValuesForNamedIDHierarchy", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        GetValuesForNamedIDHierarchyResponse GetValuesForNamedIDHierarchy(GetValuesForNamedIDHierarchyRequest request);
        [FaultContract(typeof(RequestErrorFaultType), Action="QueryCSV", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(ServerErrorFaultType), Action="QueryCSV", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="QueryCSV", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), XmlSerializerFormat(SupportFaults=true), OperationContract(Action="QueryCSV", ReplyAction="*"), ServiceKnownType(typeof(RNFault))]
        QueryCSVResponse QueryCSV(QueryCSVRequest request);
        [FaultContract(typeof(UnexpectedErrorFaultType), Action="QueryObjects", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(RequestErrorFaultType), Action="QueryObjects", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), OperationContract(Action="QueryObjects", ReplyAction="*"), FaultContract(typeof(ServerErrorFaultType), Action="QueryObjects", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        QueryObjectsResponse QueryObjects(QueryObjectsRequest request);
        [ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(RequestErrorFaultType), Action="ResetContactPassword", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="ResetContactPassword", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(ServerErrorFaultType), Action="ResetContactPassword", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), OperationContract(Action="ResetContactPassword", ReplyAction="*"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault))]
        ResetContactPasswordResponse ResetContactPassword(ResetContactPasswordRequest request);
        [OperationContract(Action="RunAnalyticsReport", ReplyAction="*"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(ServerErrorFaultType), Action="RunAnalyticsReport", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), FaultContract(typeof(RequestErrorFaultType), Action="RunAnalyticsReport", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="RunAnalyticsReport", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        RunAnalyticsReportResponse RunAnalyticsReport(RunAnalyticsReportRequest request);
        [ServiceKnownType(typeof(RNFault)), XmlSerializerFormat(SupportFaults=true), OperationContract(Action="SendMailingToContact", ReplyAction="*"), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), FaultContract(typeof(RequestErrorFaultType), Action="SendMailingToContact", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(ServerErrorFaultType), Action="SendMailingToContact", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="SendMailingToContact", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        SendMailingToContactResponse SendMailingToContact(SendMailingToContactRequest request);
        [FaultContract(typeof(ServerErrorFaultType), Action="TransferSubObjects", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(RNFault)), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), OperationContract(Action="TransferSubObjects", ReplyAction="*"), FaultContract(typeof(RequestErrorFaultType), Action="TransferSubObjects", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="TransferSubObjects", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        TransferSubObjectsResponse TransferSubObjects(TransferSubObjectsRequest request);
        [ServiceKnownType(typeof(RNFault)), FaultContract(typeof(ServerErrorFaultType), Action="Update", Name="ServerErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), FaultContract(typeof(UnexpectedErrorFaultType), Action="Update", Name="UnexpectedErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2"), XmlSerializerFormat(SupportFaults=true), ServiceKnownType(typeof(AnalyticsReportSearchFilter)), OperationContract(Action="Update", ReplyAction="*"), FaultContract(typeof(RequestErrorFaultType), Action="Update", Name="RequestErrorFault", Namespace="urn:faults.ws.rightnow.com/v1_2")]
        UpdateResponse Update(UpdateRequest request);
    }
}

